<?php 
/**
 * ACF Options
 */

if(function_exists('acf_add_options_page')) {
    
  acf_add_options_page([
    'page_title' => __('Rotating Daily Deal', 'green'),
    'menu_title' => 'Rotating Daily Deal',
    'menu_slug' => 'rotating-raily-deal-settings',
    'capability' => 'edit_posts',
    'redirect' => false
  ]);
}

if( function_exists('acf_add_local_field_group') ):

  acf_add_local_field_group(array(
    'key' => 'group_637aecf538236',
    'title' => 'Rotating Daily Deal',
    'fields' => array(
      array(
        'key' => 'field_637aed3c751b9',
        'label' => 'General Settings',
        'name' => '',
        'type' => 'tab',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'placement' => 'top',
        'endpoint' => 0,
      ),
      array(
        'key' => 'field_637aed59751ba',
        'label' => 'Enable',
        'name' => 'rdd_enable',
        'type' => 'true_false',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'message' => '',
        'default_value' => 0,
        'ui' => 1,
        'ui_on_text' => '',
        'ui_off_text' => '',
      ),
      array(
        'key' => 'field_637aedfd98cb8',
        'label' => 'Schedule Settings',
        'name' => '',
        'type' => 'tab',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'placement' => 'top',
        'endpoint' => 0,
      ),
      array(
        'key' => 'field_637af02498cb9',
        'label' => 'Monday',
        'name' => 'rdd_monday',
        'type' => 'group',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'layout' => 'block',
        'acfe_seamless_style' => 0,
        'acfe_group_modal' => 0,
        'sub_fields' => array(
          array(
            'key' => 'field_637af24598cba',
            'label' => 'Products',
            'name' => 'products',
            'type' => 'post_object',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'post_type' => array(
              0 => 'product',
            ),
            'taxonomy' => '',
            'allow_null' => 0,
            'multiple' => 1,
            'return_format' => 'object',
            'save_custom' => 0,
            'save_post_status' => 'publish',
            'acfe_bidirectional' => array(
              'acfe_bidirectional_enabled' => '0',
            ),
            'ui' => 1,
          ),
          array(
            'key' => 'field_637b1653a8afc',
            'label' => 'Deal',
            'name' => 'deal',
            'type' => 'number',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'default_value' => 0,
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'min' => '',
            'max' => '',
            'step' => '',
          ),
          array(
            'key' => 'field_637b14dd1cab4',
            'label' => 'Enable',
            'name' => 'enable',
            'type' => 'true_false',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'message' => '',
            'default_value' => 1,
            'ui' => 1,
            'ui_on_text' => '',
            'ui_off_text' => '',
          ),
        ),
      ),
      array(
        'key' => 'field_637b18c1b2207',
        'label' => 'Tuesday',
        'name' => 'rdd_tuesday',
        'type' => 'group',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'layout' => 'block',
        'acfe_seamless_style' => 0,
        'acfe_group_modal' => 0,
        'sub_fields' => array(
          array(
            'key' => 'field_637b18c1b2208',
            'label' => 'Products',
            'name' => 'products',
            'type' => 'post_object',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'post_type' => array(
              0 => 'product',
            ),
            'taxonomy' => '',
            'allow_null' => 0,
            'multiple' => 1,
            'return_format' => 'object',
            'save_custom' => 0,
            'save_post_type' => 'post',
            'save_post_status' => 'publish',
            'acfe_bidirectional' => array(
              'acfe_bidirectional_enabled' => '0',
              'acfe_bidirectional_related' => '',
            ),
            'ui' => 1,
          ),
          array(
            'key' => 'field_637b18c1b2209',
            'label' => 'Deal',
            'name' => 'deal',
            'type' => 'number',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'default_value' => 0,
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'min' => '',
            'max' => '',
            'step' => '',
          ),
          array(
            'key' => 'field_637b18c1b220a',
            'label' => 'Enable',
            'name' => 'enable',
            'type' => 'true_false',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'message' => '',
            'default_value' => 1,
            'ui' => 1,
            'ui_on_text' => '',
            'ui_off_text' => '',
          ),
        ),
      ),
      array(
        'key' => 'field_637b1901b220b',
        'label' => 'Wednesday',
        'name' => 'rdd_wednesday',
        'type' => 'group',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'layout' => 'block',
        'acfe_seamless_style' => 0,
        'acfe_group_modal' => 0,
        'sub_fields' => array(
          array(
            'key' => 'field_637b1901b220c',
            'label' => 'Products',
            'name' => 'products',
            'type' => 'post_object',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'post_type' => array(
              0 => 'product',
            ),
            'taxonomy' => '',
            'allow_null' => 0,
            'multiple' => 1,
            'return_format' => 'object',
            'save_custom' => 0,
            'save_post_type' => 'post',
            'save_post_status' => 'publish',
            'acfe_bidirectional' => array(
              'acfe_bidirectional_enabled' => '0',
              'acfe_bidirectional_related' => '',
            ),
            'ui' => 1,
          ),
          array(
            'key' => 'field_637b1901b220d',
            'label' => 'Deal',
            'name' => 'deal',
            'type' => 'number',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'default_value' => 0,
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'min' => '',
            'max' => '',
            'step' => '',
          ),
          array(
            'key' => 'field_637b1901b220e',
            'label' => 'Enable',
            'name' => 'enable',
            'type' => 'true_false',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'message' => '',
            'default_value' => 1,
            'ui' => 1,
            'ui_on_text' => '',
            'ui_off_text' => '',
          ),
        ),
      ),
      array(
        'key' => 'field_637b1923b220f',
        'label' => 'Thursday',
        'name' => 'rdd_thursday',
        'type' => 'group',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'layout' => 'block',
        'acfe_seamless_style' => 0,
        'acfe_group_modal' => 0,
        'sub_fields' => array(
          array(
            'key' => 'field_637b1923b2210',
            'label' => 'Products',
            'name' => 'products',
            'type' => 'post_object',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'post_type' => array(
              0 => 'product',
            ),
            'taxonomy' => '',
            'allow_null' => 0,
            'multiple' => 1,
            'return_format' => 'object',
            'save_custom' => 0,
            'save_post_type' => 'post',
            'save_post_status' => 'publish',
            'acfe_bidirectional' => array(
              'acfe_bidirectional_enabled' => '0',
              'acfe_bidirectional_related' => '',
            ),
            'ui' => 1,
          ),
          array(
            'key' => 'field_637b1923b2211',
            'label' => 'Deal',
            'name' => 'deal',
            'type' => 'number',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'default_value' => 0,
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'min' => '',
            'max' => '',
            'step' => '',
          ),
          array(
            'key' => 'field_637b1923b2212',
            'label' => 'Enable',
            'name' => 'enable',
            'type' => 'true_false',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'message' => '',
            'default_value' => 1,
            'ui' => 1,
            'ui_on_text' => '',
            'ui_off_text' => '',
          ),
        ),
      ),
      array(
        'key' => 'field_637b192eb2213',
        'label' => 'Friday',
        'name' => 'rdd_friday',
        'type' => 'group',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'layout' => 'block',
        'acfe_seamless_style' => 0,
        'acfe_group_modal' => 0,
        'sub_fields' => array(
          array(
            'key' => 'field_637b192eb2214',
            'label' => 'Products',
            'name' => 'products',
            'type' => 'post_object',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'post_type' => array(
              0 => 'product',
            ),
            'taxonomy' => '',
            'allow_null' => 0,
            'multiple' => 1,
            'return_format' => 'object',
            'save_custom' => 0,
            'save_post_type' => 'post',
            'save_post_status' => 'publish',
            'acfe_bidirectional' => array(
              'acfe_bidirectional_enabled' => '0',
              'acfe_bidirectional_related' => '',
            ),
            'ui' => 1,
          ),
          array(
            'key' => 'field_637b192eb2215',
            'label' => 'Deal',
            'name' => 'deal',
            'type' => 'number',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'default_value' => 0,
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'min' => '',
            'max' => '',
            'step' => '',
          ),
          array(
            'key' => 'field_637b192eb2216',
            'label' => 'Enable',
            'name' => 'enable',
            'type' => 'true_false',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'message' => '',
            'default_value' => 1,
            'ui' => 1,
            'ui_on_text' => '',
            'ui_off_text' => '',
          ),
        ),
      ),
      array(
        'key' => 'field_637b1944b2217',
        'label' => 'Saturday',
        'name' => 'rdd_saturday',
        'type' => 'group',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'layout' => 'block',
        'acfe_seamless_style' => 0,
        'acfe_group_modal' => 0,
        'sub_fields' => array(
          array(
            'key' => 'field_637b1944b2218',
            'label' => 'Products',
            'name' => 'products',
            'type' => 'post_object',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'post_type' => array(
              0 => 'product',
            ),
            'taxonomy' => '',
            'allow_null' => 0,
            'multiple' => 1,
            'return_format' => 'object',
            'save_custom' => 0,
            'save_post_type' => 'post',
            'save_post_status' => 'publish',
            'acfe_bidirectional' => array(
              'acfe_bidirectional_enabled' => '0',
              'acfe_bidirectional_related' => '',
            ),
            'ui' => 1,
          ),
          array(
            'key' => 'field_637b1944b2219',
            'label' => 'Deal',
            'name' => 'deal',
            'type' => 'number',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'default_value' => 0,
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'min' => '',
            'max' => '',
            'step' => '',
          ),
          array(
            'key' => 'field_637b1944b221a',
            'label' => 'Enable',
            'name' => 'enable',
            'type' => 'true_false',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'message' => '',
            'default_value' => 1,
            'ui' => 1,
            'ui_on_text' => '',
            'ui_off_text' => '',
          ),
        ),
      ),
      array(
        'key' => 'field_637b1953b221b',
        'label' => 'Sunday',
        'name' => 'rdd_sunday',
        'type' => 'group',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'layout' => 'block',
        'acfe_seamless_style' => 0,
        'acfe_group_modal' => 0,
        'sub_fields' => array(
          array(
            'key' => 'field_637b1953b221c',
            'label' => 'Products',
            'name' => 'products',
            'type' => 'post_object',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'post_type' => array(
              0 => 'product',
            ),
            'taxonomy' => '',
            'allow_null' => 0,
            'multiple' => 1,
            'return_format' => 'object',
            'save_custom' => 0,
            'save_post_type' => 'post',
            'save_post_status' => 'publish',
            'acfe_bidirectional' => array(
              'acfe_bidirectional_enabled' => '0',
              'acfe_bidirectional_related' => '',
            ),
            'ui' => 1,
          ),
          array(
            'key' => 'field_637b1953b221d',
            'label' => 'Deal',
            'name' => 'deal',
            'type' => 'number',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'default_value' => 0,
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'min' => '',
            'max' => '',
            'step' => '',
          ),
          array(
            'key' => 'field_637b1953b221e',
            'label' => 'Enable',
            'name' => 'enable',
            'type' => 'true_false',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'message' => '',
            'default_value' => 1,
            'ui' => 1,
            'ui_on_text' => '',
            'ui_off_text' => '',
          ),
        ),
      ),
    ),
    'location' => array(
      array(
        array(
          'param' => 'options_page',
          'operator' => '==',
          'value' => 'rotating-raily-deal-settings',
        ),
      ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'left',
    'instruction_placement' => 'field',
    'hide_on_screen' => '',
    'active' => true,
    'description' => '',
    'acfe_display_title' => '',
    'acfe_autosync' => '',
    'acfe_form' => 0,
    'acfe_meta' => '',
    'acfe_note' => '',
  ));
  
endif;